spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 641238456473-36dsj53541is0bti1fbrq82pgnnd9m0e.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            client-name: Google